name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    name: Release
    runs-on: macos-15
    steps:
      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Build and Archive App
        run: |
          xcodebuild -scheme GitClient -configuration Release -archivePath Tempo.xcarchive archive
          xcodebuild -exportArchive -archivePath GitClient.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath Tempo
      - name: Notarize App
        env:
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        run: |
          xcrun notarytool submit Tempo/Tempo.app --apple-id "$AC_USERNAME" --password "$AC_PASSWORD" --team-id JRA6VW2DG4 --wait
      - name: Create ZIP Archive
        run: |
          ditto -c -k --keepParent Tempo/Tempo.app Tempo.zip
      - name: Generate SHA256 Checksum
        run: |
          shasum -a 256 Tempo.zip > Tempo.zip.sha256.txt
          echo "SHA256 Checksum: $(cat Tempo.zip.sha256.txt)" >> $GITHUB_STEP_SUMMARY
      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            Tempo.zip
            Tempo.zip.sha256.txt
          draft: true
          generate_release_notes: true
