name: test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Test
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check PATH
        run: |
          echo $PATH
      - name: Check git
        run: |
          which git
      - name: Check git version
        run: |
          git --version
      - name: Set PATH for Git
        run: |
          export PATH="/opt/homebrew/bin:$PATH"
      - name: Test
        run: |
          xcodebuild clean test -scheme GitClient CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=macOS" -disableAutomaticPackageResolution
